# Использование образа Java
FROM openjdk:11
# Установка рабочей директории внутри контейнера 
WORKDIR /usr/src/app
# Копирование исходного кода в контейнер
COPY calc.java .
# Компиляция java-приложения
RUN javac calc.java
# Запуск приложения
CMD ["java", "calc"]